package com.etecnologic.bridge.model;
// Generated 04-nov-2017 17:59:44 by Hibernate Tools 5.2.6.Final

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * Users generated by hbm2java
 */
@Document(collection = "user")
public class User {

	@Id
	private Integer id;
	private String username;
	private String password;

	public User() {
	}

	public User(String userName, String password) {
		this.setUsername(username);
		this.password = password;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
